name: Test Ansible workflow

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add Ubuntu repo
      uses: myci-actions/add-deb-repo@10
      with:
        repo: deb http://it.archive.ubuntu.com/ubuntu/ focal main universe restricted multiverse
        repo-name: Deb
        
    - name: Add Ubuntu repo
      uses: myci-actions/add-deb-repo@10
      with:
        repo: deb-src http://it.archive.ubuntu.com/ubuntu/ focal main universe restricted multiverse
        repo-name: Deb-src
    
    - name: Install pip and download ansible navigator
      run: |
        pip3 install ansible-navigator 
