name: Test Ansible workflow

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add Ubuntu repo
      uses: myci-actions/add-deb-repo@10
      with:
        repo: http://it.archive.ubuntu.com/ubuntu/ focal main universe restricted multiverse
        repo-name: Deb
        
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        # Required, playbook filepath
        playbook: main.yml
        # Optional, directory where playbooks live
        directory: ./
        requirements: requirements.yml
        options: |
          --verbose
